### ISSUE TITLE
Не абнаўляецца імя

### ISSUE THREAD

**Issue by rageofaxe** [nishoby/nisho#10]
Navbar.vue / updateUserName

```
    const { data, error } = await supabase.auth.updateUser({
        data: {
            username: username.trim(),
        },
    });
```

тут разам з username трэ перадаваць name, бо ў мадэлі выкарыстоўваецца таксама name
`accountName.value = data.user.user_metadata.name;`

**Comment by rizomaa** [comment]
@rageofaxe 

Тут таксама  Будзем удзячны пулрэквэсту з патрэбным кода.
Дзякуй вам.

**Comment by alherd-by** [comment]
@rageofaxe вы гэта кажаце толькі па code review, ці ў вас не працуе?

Бо калі першае, то гэта зроблена мэтанакіравана, ёсць патрэба ў гэтым на бэкенде

**Comment by alherd-by** [comment]
Выправлена тут https://github.com/nishoby/nisho/pull/16
