### ISSUE TITLE
Лексічная памылка

### ISSUE THREAD

**Issue by rageofaxe** [nishoby/nisho#11]
Navbar.vue / updateUserName

```
    if (error) {
        ElMessage.error('Праізашла памылка ў логіцы працы праграммы, не турбуйцеся, вы ўсе зрабілі правільна');
        throw error;
    }
```
Усё ж такі не "Праізашла", а "Адбылася" або "Сталася"

**Comment by rizomaa** [comment]
@rageofaxe прывітанне,

У нас не хапае рук, калі вы шарыце ў кодзе, будзем удзячны пулрэквэсту з патрэбным тэкстам.
Дзякуй вам.

**Comment by alherd-by** [comment]
Выправілі ў https://github.com/nishoby/nisho/commit/b5a1b6175f8fa1be9f233090d7a92e90d460b622
