### ISSUE TITLE
месяцы паехалі

### ISSUE THREAD

**Issue by loshurik** [nishoby/nisho#2]
словы ад траўня (дата стаіць) падпісаны як чэрвеньскія
![image](https://github.com/nishoby/nisho/assets/1557456/d1666edf-08ee-4c3c-951d-959d1b206caa)

**Comment by mihaspaulavich** [comment]
выпраўлена
<img width="357" alt="image" src="https://github.com/nishoby/nisho/assets/125358847/58561f9f-d647-4ec2-8d4b-f1315e50dc59">
