### ISSUE TITLE
Іконка "Паскардзіца" плавае над хэдэрам

### ISSUE THREAD

**Issue by mikitakalinovsky** [nishoby/nisho#24]
браўзер: opera gx;
плятформа: macos ventura

https://github.com/nishoby/nisho/assets/71591796/0ab4f1ef-456a-403f-90a1-e4f56053075e

**Comment by mikitakalinovsky** [comment]
upd: safari і chrome - парадак

**Comment by mihaspaulavich** [comment]
Не магу знайсці гэты баг. Сістэма і браўзэр супадаюць з Вашымі. Гэтак жа не бачу ў кодзе нічога, што магло яго выклікаць.
<img width="229" alt="image" src="https://github.com/nishoby/nisho/assets/125358847/752fc279-1856-4b08-800a-2d897b4ac336">

Я зачыню гэтую задачу, бо яна малаверагодная і ня вельмі крытычная.
