### ISSUE TITLE
Спасылка на дыскорд памерла

### ISSUE THREAD

**Issue by nkapultsevich** [nishoby/nisho#40]
Дадайце, калі ласка, працоўную, альбо выдаліце з сайту. Бо мёртвыя спасылкі заўсёды наводзяць на думкі, што сайтам не займаюцца.
<img width="514" alt="image" src="https://github.com/nishoby/nisho/assets/62237487/64bf351a-f42d-4472-95ef-4e7d400bcecd">
<img width="348" alt="image" src="https://github.com/nishoby/nisho/assets/62237487/20068293-eac9-4b3c-b4d1-edc911f24c0e">

**Comment by rizomaa** [comment]
Вось актуальная https://discord.gg/YDyDdJY6

**Comment by MoskKir** [comment]
PR: https://github.com/nishoby/nisho/pull/46

**Comment by alherd-by** [comment]
Папраўлена
