### ISSUE TITLE
Дадаць іконку інстаграма у футары каля дыскарда.

### ISSUE THREAD

**Issue by rizomaa** [nishoby/nisho#44]
Вось лінк https://www.instagram.com/nisho_slounik/

**Comment by MoskKir** [comment]
https://github.com/nishoby/nisho/pull/45

**Comment by alherd-by** [comment]
Выпраўлена тут https://github.com/nishoby/nisho/commit/10eb4cc11f9c0a328f6e497b603f2dfc191282cd
