### ISSUE TITLE
Не паказвае ўсіх карыстачоў у адмінцы.

### ISSUE THREAD

**Issue by rizomaa** [nishoby/nisho#64]
Нейкі баг маем. Блакуючы. 

У адмінцы не паказвае больш за 5 старонак зарэгістраваных карыстачоў. Апошнія, якія бачныя зарэгістраваныя 29 чэрвеня. Але словы пачалі дадаваць розныя карыстальнікі ўжо 12 чэрвеня. Значыць дзесці пазнікала больш за два тыдня карыстачоў. 

![nisho-dashboard](https://github.com/nishoby/nisho/assets/9870374/bd49543f-a820-4242-94e3-c4d801fce1b2)

**Comment by alherd-by** [comment]
Выпраўлена
