### ISSUE TITLE
Зрабіць падкачку превью, сайта, калі дзесці пакінуты лінк 

### ISSUE THREAD

**Issue by svetit** [nishoby/nisho#7]
![IMG_20230613_112651](https://github.com/nishoby/nisho/assets/1722996/9d9e437b-6cf5-4389-81c9-a334d04815ea)
Вось напрыклад я пакідаю лінк на сайт і хачу, каб распаршывалася превью.
Гэта прыгожа і больш прыцягвае увагі людзей.
На превью будзе крута лого і дзевачка
![FB_IMG_1686578358056](https://github.com/nishoby/nisho/assets/1722996/ab6162aa-5eb6-459f-876c-992507ba3ddb)

**Comment by alherd-by** [comment]
Зроблена ў https://github.com/nishoby/nisho/commit/255ee1209ee14c852b3168cf6799c43c4b4b7311
